// Auto-generated file. Do not edit manually.

export const mediaList = {
  images: {
  "root": [
    "/images/background.png",
    "/images/bg1!.png",
    "/images/bg1.png",
    "/images/bg2.png",
    "/images/coming.gif",
    "/images/main1.jpg",
    "/images/next.png",
    "/images/previous.png"
  ],
  "Rana's What's app Photos": [
    "/images/Rana's What's app Photos/1st Ganpati outfit.jpeg",
    "/images/Rana's What's app Photos/1st Ganpati.jpeg",
    "/images/Rana's What's app Photos/1zn2rtMfXW7vh5ID9SNmWRNr6yKe53zvKP-ltpH3SWE=_plaintext_638203426794763696.jpg",
    "/images/Rana's What's app Photos/3 in one. Eating his fingers, crying and holding mama chin - all at same time.jpeg",
    "/images/Rana's What's app Photos/4 Jain Generations.jpg",
    "/images/Rana's What's app Photos/4WvoGZ-WvUCDkoDPNOoSA1112KhGVeCQw3vjvQMzxQ8=_plaintext_638203427461441609.jpg",
    "/images/Rana's What's app Photos/5hD61k8mMlcs5aCz37jpkl7_DhAbX4XpAHqqTBgzi-Q=_plaintext_638203428746966653.jpg",
    "/images/Rana's What's app Photos/5uEymynf_RAa4gINxbMNRwwWDRUPpiiNjIV_MjN1WNk=_plaintext_638203426853026636.jpg",
    "/images/Rana's What's app Photos/6 teeth ..before 8 mths.jpeg",
    "/images/Rana's What's app Photos/9hkXAgGdhfOr0YpIuS05gk536GgMWa8bk5DjuCL0KYM=_plaintext_638203426528652212.jpg",
    "/images/Rana's What's app Photos/AeQZIJ4sPUchbi6rWtMbfC_6_7h_Ls9G_Flcy7MLfNQ=_plaintext_638203426826978855.jpg",
    "/images/Rana's What's app Photos/All dressed up to go for 1st Bday Party.jpeg",
    "/images/Rana's What's app Photos/All lattoo over our laddoo.jpeg",
    "/images/Rana's What's app Photos/Amahle and bada Nana- So comfortable.jpeg",
    "/images/Rana's What's app Photos/Anissa ditto.jpeg",
    "/images/Rana's What's app Photos/Babas looking after baba.jpeg",
    "/images/Rana's What's app Photos/Being Born.jpg",
    "/images/Rana's What's app Photos/BhXCpQas2MXJ4N-zBRzP_0nPTmwcFA7HyUA0UWobCzs=_plaintext_638203426801971210.jpg",
    "/images/Rana's What's app Photos/Big  Boy in Polo.jpeg",
    "/images/Rana's What's app Photos/Bullied by younger sister.jpeg",
    "/images/Rana's What's app Photos/Crumpled Peace.jpg",
    "/images/Rana's What's app Photos/Crying Day 5.jpg",
    "/images/Rana's What's app Photos/D0YOjfpW1WBXQBcpn38Lh8VQGT3gjf8Xn6sizuyfvZg=_plaintext_638203426838967629.jpg",
    "/images/Rana's What's app Photos/Dadi Massage.jpeg",
    "/images/Rana's What's app Photos/Dekh Bhai..deal karni hai ya nahi.jpeg",
    "/images/Rana's What's app Photos/Epic Staring.jpeg",
    "/images/Rana's What's app Photos/Eyeballing ea other !.jpeg",
    "/images/Rana's What's app Photos/First Halloween- Pumpkin Boy.jpeg",
    "/images/Rana's What's app Photos/Ganja Baba.jpeg",
    "/images/Rana's What's app Photos/Ganpati cheer 1.jpeg",
    "/images/Rana's What's app Photos/Ganpati cheer.jpeg",
    "/images/Rana's What's app Photos/gDjXSuFN5SnfqDjS-Vxku6lf4Gmvz8DldOr6ocRe2sQ=_plaintext_638203426891521913.jpg",
    "/images/Rana's What's app Photos/Good Morning.jpeg",
    "/images/Rana's What's app Photos/Good Student.jpeg",
    "/images/Rana's What's app Photos/Gtg ready for World Cup Cricket Final.jpeg",
    "/images/Rana's What's app Photos/Gujarati Boss... no shoes in offc 😝.jpeg",
    "/images/Rana's What's app Photos/gWgDBB0mKF6r65ucMK7sZMDGKURNWCrab_aNJjXlBRY=_plaintext_638203427527487704.jpg",
    "/images/Rana's What's app Photos/h0zF6H_4EosxPiJcjFvXfaEnOK--cuSxX1ZA0fhV1Mc=_plaintext_638203426827511966.jpg",
    "/images/Rana's What's app Photos/Halloween with cousin Raha.jpeg",
    "/images/Rana's What's app Photos/Happy Baby Happy Ma.jpeg",
    "/images/Rana's What's app Photos/Happy between Mummy and Mummy's Mummy.jpeg",
    "/images/Rana's What's app Photos/Happy Diner!.jpeg",
    "/images/Rana's What's app Photos/Happy Hum.jpeg",
    "/images/Rana's What's app Photos/Happy Rana 1st Divali Family 🩷🪔.jpeg",
    "/images/Rana's What's app Photos/Happy with his books.jpeg",
    "/images/Rana's What's app Photos/Happy with Nana.jpeg",
    "/images/Rana's What's app Photos/hCWn9RiXggm8V6LjQs9EcYSqs1PSqH33CdGiuXVgwuU=_plaintext_638203426848098053.jpg",
    "/images/Rana's What's app Photos/He can't crawl but can stand..  kya aadmi hai.jpeg",
    "/images/Rana's What's app Photos/His 1st Teddy Bear.jpeg",
    "/images/Rana's What's app Photos/His first teeth before 5 mths - ahead of time.jpeg",
    "/images/Rana's What's app Photos/His Mama's  Baby Ditto Doppelganger.jpeg",
    "/images/Rana's What's app Photos/I go where you go . Ma & Baby.jpeg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0013.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0014.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0015.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0016.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0017.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0018.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0019.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0020.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0021.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0022.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0023.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0024.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0025.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0026.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0027.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0028.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0029.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0030.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0031.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0032.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0033.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0034.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0035.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0036.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0037.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0038.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0039.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0040.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0041.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0042.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0043.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0044.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0045.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0046.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0047.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0048.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0049.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0050.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0051.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0052.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0053.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0054.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0055.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0056.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0057.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0058.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0059.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0060.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0061.jpg",
    "/images/Rana's What's app Photos/IMG-20230522-WA0062.jpg",
    "/images/Rana's What's app Photos/In Tandem.jpeg",
    "/images/Rana's What's app Photos/In the pool 1.jpeg",
    "/images/Rana's What's app Photos/Inspection team with his sister.jpeg",
    "/images/Rana's What's app Photos/Jungle Baby.jpeg",
    "/images/Rana's What's app Photos/Kya Baat Hai Bhai",
    "/images/Rana's What's app Photos/kz-Axcf_VHNOp5_km0O6zDxSjihCDRvUmpViKjeA2OQ=_plaintext_638203427515853156.jpg",
    "/images/Rana's What's app Photos/Learning to stand.jpeg",
    "/images/Rana's What's app Photos/Lil Santa.jpeg",
    "/images/Rana's What's app Photos/Little RK.jpeg",
    "/images/Rana's What's app Photos/Look at the two scared dodos.jpeg",
    "/images/Rana's What's app Photos/Lost in tne wild.jpeg",
    "/images/Rana's What's app Photos/Mini Sumo Wrestler by face !!.jpeg",
    "/images/Rana's What's app Photos/Mother ( light) Theresa.jpeg",
    "/images/Rana's What's app Photos/mtgBj11043uua_SzrCnZMciBYJzvg8uR3taf7Vogy9I=_plaintext_638203426813481408.jpg",
    "/images/Rana's What's app Photos/My Baby (2).jpeg",
    "/images/Rana's What's app Photos/My Baby.jpeg",
    "/images/Rana's What's app Photos/My Big Boy.jpeg",
    "/images/Rana's What's app Photos/My Boy @ 6 mths.jpeg",
    "/images/Rana's What's app Photos/My Boy.jpeg",
    "/images/Rana's What's app Photos/My Cleopatra.jpeg",
    "/images/Rana's What's app Photos/My Collared Boy .jpg",
    "/images/Rana's What's app Photos/My happy Baby.jpeg",
    "/images/Rana's What's app Photos/My Pizza Face bandar.jpeg",
    "/images/Rana's What's app Photos/My Polo boy (2).jpeg",
    "/images/Rana's What's app Photos/My Polo Boy.jpeg",
    "/images/Rana's What's app Photos/My studious boy.jpeg",
    "/images/Rana's What's app Photos/Nana Rana @ Ganpati Darshan.jpeg",
    "/images/Rana's What's app Photos/Nanga Haathjod.jpeg",
    "/images/Rana's What's app Photos/Nanga Pahlwan 3.jpeg",
    "/images/Rana's What's app Photos/Nanga Pahlwan.jpeg",
    "/images/Rana's What's app Photos/Nanga Pahlwan2.jpeg",
    "/images/Rana's What's app Photos/Nanga panga.jpeg",
    "/images/Rana's What's app Photos/Naughty finger!  With a smile.jpeg",
    "/images/Rana's What's app Photos/Neck Sighting.jpeg",
    "/images/Rana's What's app Photos/New Pizza Face.jpeg",
    "/images/Rana's What's app Photos/NOT looking like a Rana.jpeg",
    "/images/Rana's What's app Photos/np--ZWNAd2lizdsmF5_rerGJFbHlvHEdMQMt8OQO0dc=_plaintext_638203426815299256.jpg",
    "/images/Rana's What's app Photos/Oh Ooh.jpg",
    "/images/Rana's What's app Photos/One mouthful.jpeg",
    "/images/Rana's What's app Photos/Our Mota Bhai.jpeg",
    "/images/Rana's What's app Photos/Outside the famous 107.jpeg",
    "/images/Rana's What's app Photos/Patience !! Fellow Board Members.jpeg",
    "/images/Rana's What's app Photos/Pretty Amahle.jpeg",
    "/images/Rana's What's app Photos/Punjabi Seeti.jpeg",
    "/images/Rana's What's app Photos/r4iM8caDeeEwsP9_9lvhiUUnmPCu-ILE-3uAME_igrE=_plaintext_638203427530844045.jpg",
    "/images/Rana's What's app Photos/Raha - Rana orchestra !! Tandem Crying with his cousin !!.jpeg",
    "/images/Rana's What's app Photos/Rana & Nana.jpeg",
    "/images/Rana's What's app Photos/Rana 1st Xmas lunch.jpeg",
    "/images/Rana's What's app Photos/Rana @ 5 mths.jpeg",
    "/images/Rana's What's app Photos/Rana Anissa Smile Arctic.jpg",
    "/images/Rana's What's app Photos/Rana first sitting up - by himself without anyone’s help!!!!.jpeg",
    "/images/Rana's What's app Photos/Rana Sandwich.jpeg",
    "/images/Rana's What's app Photos/Rana's 1st Cuddly Toy.jpeg",
    "/images/Rana's What's app Photos/Ranas Nana.jpeg",
    "/images/Rana's What's app Photos/Same expression as RK.jpeg",
    "/images/Rana's What's app Photos/Santa & his tree.jpeg",
    "/images/Rana's What's app Photos/Serious conversation with friends.jpeg",
    "/images/Rana's What's app Photos/Shining Roundly.jpeg",
    "/images/Rana's What's app Photos/Sitting Solo Cowboy.jpeg",
    "/images/Rana's What's app Photos/Sleeping like an adult.jpg",
    "/images/Rana's What's app Photos/Sleeping Raja Rana.jpeg",
    "/images/Rana's What's app Photos/Sleeping Smiler.jpg",
    "/images/Rana's What's app Photos/Smiler.jpeg",
    "/images/Rana's What's app Photos/Smiling Sleeping Little Buddha.jpeg",
    "/images/Rana's What's app Photos/Someone pl find my neck.jpeg",
    "/images/Rana's What's app Photos/Someones Cellulite Bum.jpeg",
    "/images/Rana's What's app Photos/SPekq8ysM7atrEmeUc-8BCW5C-VcmdhWKdI-rBUS6B0=_plaintext_638203426585326690.jpg",
    "/images/Rana's What's app Photos/Squareface Rana Outline.jpg",
    "/images/Rana's What's app Photos/Supporting his parents.jpeg",
    "/images/Rana's What's app Photos/Tennis Boy Shorts.jpeg",
    "/images/Rana's What's app Photos/The Boss.jpeg",
    "/images/Rana's What's app Photos/The Monk.jpg",
    "/images/Rana's What's app Photos/The Prince on his throne.jpeg",
    "/images/Rana's What's app Photos/The sleepy smiler.jpg",
    "/images/Rana's What's app Photos/Thoda Dukhi Batman.jpeg",
    "/images/Rana's What's app Photos/Twins Sleeping.jpeg",
    "/images/Rana's What's app Photos/Ulta langoor.jpeg",
    "/images/Rana's What's app Photos/WduYIrls8yBaVjYF9cveA4vUvviAyEj4_PxqBl30jSs=_plaintext_638203427473031350.jpg",
    "/images/Rana's What's app Photos/What you doing with me.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-05-31 at 07.29.33.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-07-18 at 11.45.18.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-07-18 at 11.45.33.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-07-18 at 11.45.57.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-07-18 at 11.47.03.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-07-18 at 11.47.16.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-07-18 at 11.47.34.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-08-22 at 10.28.17.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-08-22 at 10.35.30.jpeg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-09-11 at 00.26.19.jpg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-09-11 at 00.29.06.jpg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-09-11 at 00.29.07.jpg",
    "/images/Rana's What's app Photos/WhatsApp Image 2023-09-11 at 00.29.10.jpg",
    "/images/Rana's What's app Photos/Wide Cheeks.jpg",
    "/images/Rana's What's app Photos/Widest Cheeks.jpg",
    "/images/Rana's What's app Photos/With his cousin n bhua.jpeg",
    "/images/Rana's What's app Photos/With Uncle Kjo.jpeg",
    "/images/Rana's What's app Photos/Worst Passport Pic in Guiness Records.jpg",
    "/images/Rana's What's app Photos/Wrestling with Nana.jpeg",
    "/images/Rana's What's app Photos/x1aMNPBRZmBgsqHiLA0wbfkq-xjShN60BZikbVOBcsU=_plaintext_638203427464070605.jpg",
    "/images/Rana's What's app Photos/xKYgIVIRMSmqC9u2bVMSBgajFuHc0p7poBwBeQPnlYk=_plaintext_638203426863031034.jpg",
    "/images/Rana's What's app Photos/ZO1t5Ew_IPL2hf8R9xRwmkYq0XZWJo8LPaAkFRQgm-o=_plaintext_638203427519096122.jpg",
    "/images/Rana's What's app Photos/मोटा Seth.jpeg",
    "/images/Rana's What's app Photos/मोटा,मोटा seth.jpeg"
  ],
  "Rana's What's app Videos": [
    "/images/Rana's What's app Videos/1st Change Nanga.mp4",
    "/images/Rana's What's app Videos/1st Ganpati Matha teko.mp4",
    "/images/Rana's What's app Videos/1st Tummy Time.mp4",
    "/images/Rana's What's app Videos/2nd place - yippee.mp4",
    "/images/Rana's What's app Videos/3 min laugh attack with his Pa.mp4",
    "/images/Rana's What's app Videos/A compendium of many faces.mp4",
    "/images/Rana's What's app Videos/Aarti Thali with  his ma & pa.mp4",
    "/images/Rana's What's app Videos/Adidas athlete in a lap.mp4",
    "/images/Rana's What's app Videos/Athletic - Plank Master before six months.mp4",
    "/images/Rana's What's app Videos/Best gift ever from rana to nana🩷.mp4",
    "/images/Rana's What's app Videos/Bharat Natyam Eyes.mp4",
    "/images/Rana's What's app Videos/Big Boy trying to sleep on his own !!.mp4",
    "/images/Rana's What's app Videos/Big Potty.mp4",
    "/images/Rana's What's app Videos/Both Hands Squirming Lovely.mp4",
    "/images/Rana's What's app Videos/Bubbly Dubbly 2.mp4",
    "/images/Rana's What's app Videos/Bubbly Dubbly.mp4",
    "/images/Rana's What's app Videos/Bugs Bunny Clucking.mp4",
    "/images/Rana's What's app Videos/Car Talks.mp4",
    "/images/Rana's What's app Videos/Chatting with Badi Dadi.mp4",
    "/images/Rana's What's app Videos/Christmas Baba.mp4",
    "/images/Rana's What's app Videos/Conversations with Nana.mp4",
    "/images/Rana's What's app Videos/Crawling to ma.mp4",
    "/images/Rana's What's app Videos/Cricketer in house.mp4",
    "/images/Rana's What's app Videos/Crying in Sleep.mp4",
    "/images/Rana's What's app Videos/Cute, shy, gurgley - with push ups.mp4",
    "/images/Rana's What's app Videos/Day 1 after solids - he wants food on his table!!.mp4",
    "/images/Rana's What's app Videos/Doubly Bubbly × Double.mp4",
    "/images/Rana's What's app Videos/Drinking Problem.mp4",
    "/images/Rana's What's app Videos/Dudhu pee le.mp4",
    "/images/Rana's What's app Videos/Eating hands.mp4",
    "/images/Rana's What's app Videos/Evening Work Out.mp4",
    "/images/Rana's What's app Videos/Excited about food.mp4",
    "/images/Rana's What's app Videos/Eyes that Pierce.mp4",
    "/images/Rana's What's app Videos/Face Therapy For ME.mp4",
    "/images/Rana's What's app Videos/Fast Mover.mp4",
    "/images/Rana's What's app Videos/First Clsss from Nana - Tongue.mp4",
    "/images/Rana's What's app Videos/First forward crawl.mp4",
    "/images/Rana's What's app Videos/First Neck Sighting.mp4",
    "/images/Rana's What's app Videos/First Pair of Teeth.mp4",
    "/images/Rana's What's app Videos/First Xmas of our Babies.mp4",
    "/images/Rana's What's app Videos/Fists & Faces - Rana Ke naatakein.mp4",
    "/images/Rana's What's app Videos/Focused studying.mp4",
    "/images/Rana's What's app Videos/Found his feet.mp4",
    "/images/Rana's What's app Videos/Full house.mp4",
    "/images/Rana's What's app Videos/Giggly Goo.mp4",
    "/images/Rana's What's app Videos/Going Mad Laughing.mp4",
    "/images/Rana's What's app Videos/Going Nanga Crazy!!!!!!!!!!!!!!!!!!!.mp4",
    "/images/Rana's What's app Videos/Goodnight from wee willy Rana.mp4",
    "/images/Rana's What's app Videos/Goodnight from wee willy Rana2.mp4",
    "/images/Rana's What's app Videos/Half a year Birthday - 1st Solid food..mp4",
    "/images/Rana's What's app Videos/Happy Bather!!.mp4",
    "/images/Rana's What's app Videos/Happy I  his crib.mp4",
    "/images/Rana's What's app Videos/Happy musucal 7 to mee😜😜tabla class.mp4",
    "/images/Rana's What's app Videos/Happy on Papa's Birthday.mp4",
    "/images/Rana's What's app Videos/Heads Up.mp4",
    "/images/Rana's What's app Videos/Hi & bye our standing boy.mp4",
    "/images/Rana's What's app Videos/His first Jhoola !!.mp4",
    "/images/Rana's What's app Videos/Horizontal Shrieking.mp4",
    "/images/Rana's What's app Videos/I can  smile too.mp4",
    "/images/Rana's What's app Videos/In conv with Mammy.mp4",
    "/images/Rana's What's app Videos/In my Runwal home.mp4",
    "/images/Rana's What's app Videos/Incredible Seville at almost 11 pm at night.  LOVE IT.mp4",
    "/images/Rana's What's app Videos/Infectious fishy laughter 🥰.mp4",
    "/images/Rana's What's app Videos/Jeetega India.mp4",
    "/images/Rana's What's app Videos/Laughing at the lamp.mp4",
    "/images/Rana's What's app Videos/Learning Dhol already.mp4",
    "/images/Rana's What's app Videos/Learning to crawl with his Pa.mp4",
    "/images/Rana's What's app Videos/Little Tadpole.mp4",
    "/images/Rana's What's app Videos/Love him so much.mp4",
    "/images/Rana's What's app Videos/Lullaby Laddoo Serenity.mp4",
    "/images/Rana's What's app Videos/Mahendra Bhai Chewing Pan.mp4",
    "/images/Rana's What's app Videos/Making elder filmy kids play.mp4",
    "/images/Rana's What's app Videos/Mama’s tribute to wee willy.mp4",
    "/images/Rana's What's app Videos/Masti  Master.mp4",
    "/images/Rana's What's app Videos/Mirror Talks.mp4",
    "/images/Rana's What's app Videos/Mirror Talks2.mp4",
    "/images/Rana's What's app Videos/Missed his Papa.mp4",
    "/images/Rana's What's app Videos/More Confident Goonda standing up 🥰.mp4",
    "/images/Rana's What's app Videos/Morning Class 1.mp4",
    "/images/Rana's What's app Videos/Morning Exercise.mp4",
    "/images/Rana's What's app Videos/Mummy ka smile.mp4",
    "/images/Rana's What's app Videos/MY ABSOLUTELY No 1 video of my Baba😍 🧿.mp4",
    "/images/Rana's What's app Videos/My Ganju Prawn at 2 days.mp4",
    "/images/Rana's What's app Videos/My innocent boy.mp4",
    "/images/Rana's What's app Videos/Nama & Wee Willie.mp4",
    "/images/Rana's What's app Videos/Nana 1st Story Telling Session.mp4",
    "/images/Rana's What's app Videos/Nana feeding Rana.mp4",
    "/images/Rana's What's app Videos/Nana Whistling.mp4",
    "/images/Rana's What's app Videos/Nanga Panga Feet & Pizza Face.mp4",
    "/images/Rana's What's app Videos/Nanis Happy Baby.mp4",
    "/images/Rana's What's app Videos/Never forget this video.mp4",
    "/images/Rana's What's app Videos/Never seen him cry.mp4",
    "/images/Rana's What's app Videos/No way out.mp4",
    "/images/Rana's What's app Videos/On the shoulder 1st time.mp4",
    "/images/Rana's What's app Videos/Our little bakree.mp4",
    "/images/Rana's What's app Videos/Our Vidvaan Rana.mp4",
    "/images/Rana's What's app Videos/Outgrow Ship.mp4",
    "/images/Rana's What's app Videos/Peaceful with Pink.mp4",
    "/images/Rana's What's app Videos/Plank master with dry  swimming.mp4",
    "/images/Rana's What's app Videos/Poora Pagal.mp4",
    "/images/Rana's What's app Videos/Pottify - Masterpiece of Bonding.mp4",
    "/images/Rana's What's app Videos/Punjabi Seeti.mp4",
    "/images/Rana's What's app Videos/Rana 1st Aarti.mp4",
    "/images/Rana's What's app Videos/Rana 1st Ganpati Darshan.mp4",
    "/images/Rana's What's app Videos/Rana 1st jhoola.mp4",
    "/images/Rana's What's app Videos/Rana 1st Piano Class.mp4",
    "/images/Rana's What's app Videos/Rana 1st play with dogs !!.mp4",
    "/images/Rana's What's app Videos/Rana @ Aarti Thali.mp4",
    "/images/Rana's What's app Videos/Rana can I come in.mp4",
    "/images/Rana's What's app Videos/Rana Hi.mp4",
    "/images/Rana's What's app Videos/Rana in the mirror.mp4",
    "/images/Rana's What's app Videos/Rana Jain getting his hands on his first drink !!.mp4",
    "/images/Rana's What's app Videos/Rana Means a Froggie.mp4",
    "/images/Rana's What's app Videos/Rana puts the final signature on! Here’s to armaans relentless pursuit, hard work and passion. And here’s to dining with the Kapoor’s 💫🍻🥂 we are so so proud of you and them Aavashyak.mp4",
    "/images/Rana's What's app Videos/Rana's 1st driving lesson.mp4",
    "/images/Rana's What's app Videos/Rana's first mauli and offc pooja🙏🙏🕉️🕉️.mp4",
    "/images/Rana's What's app Videos/Rana's1st Jhoola.mp4",
    "/images/Rana's What's app Videos/Rana1st Tummy time.mp4",
    "/images/Rana's What's app Videos/Rapid Crawl to Nana.mp4",
    "/images/Rana's What's app Videos/Rattled with laughter.mp4",
    "/images/Rana's What's app Videos/Responding to his Mummy.mp4",
    "/images/Rana's What's app Videos/Responding.mp4",
    "/images/Rana's What's app Videos/Rrrrana by Armaan.mp4",
    "/images/Rana's What's app Videos/Screaming Banshee.mp4",
    "/images/Rana's What's app Videos/Shaky Shaky.mp4",
    "/images/Rana's What's app Videos/Sitting up at 85 days.mp4",
    "/images/Rana's What's app Videos/Sleep Shy.mp4",
    "/images/Rana's What's app Videos/Sleeping Ring tone.mp4",
    "/images/Rana's What's app Videos/Sleeping Smiler Fisheye.mp4",
    "/images/Rana's What's app Videos/Sleeping Sucker.mp4",
    "/images/Rana's What's app Videos/Sleepy Ringtone.mp4",
    "/images/Rana's What's app Videos/Smile On demand.mp4",
    "/images/Rana's What's app Videos/Smiler in a boat.mp4",
    "/images/Rana's What's app Videos/Squareface Rana.mp4",
    "/images/Rana's What's app Videos/Squealing with Nana.mp4",
    "/images/Rana's What's app Videos/Standing up on his own (very early) first time my baba.mp4",
    "/images/Rana's What's app Videos/Talking to his papa.mp4",
    "/images/Rana's What's app Videos/Talking to Nana.mp4",
    "/images/Rana's What's app Videos/Talks with Nana.mp4",
    "/images/Rana's What's app Videos/Tet a tet with Badi Dadi.mp4",
    "/images/Rana's What's app Videos/The Air Eater - Extended Play.mp4",
    "/images/Rana's What's app Videos/The Air Eater.mp4",
    "/images/Rana's What's app Videos/The Bum Crawl - tamatar mazedar.mp4",
    "/images/Rana's What's app Videos/The Crying sausage.mp4",
    "/images/Rana's What's app Videos/The Junior Jains are chilling !!.mp4",
    "/images/Rana's What's app Videos/The Teaser Cock ❤️.mp4",
    "/images/Rana's What's app Videos/Thoda Pagal - laughing at Lamps n Rivets last one month.mp4",
    "/images/Rana's What's app Videos/Thoda Pagal 2.mp4",
    "/images/Rana's What's app Videos/Thoda Pagal.mp4",
    "/images/Rana's What's app Videos/Total Pagal.mp4",
    "/images/Rana's What's app Videos/Tug of war.mp4",
    "/images/Rana's What's app Videos/Tug of war2.mp4",
    "/images/Rana's What's app Videos/Tummy Laughs with Rima.mp4",
    "/images/Rana's What's app Videos/Twoink.mp4",
    "/images/Rana's What's app Videos/Unbundled Nani Bday.mp4",
    "/images/Rana's What's app Videos/VID-20230522-WA0008.mp4",
    "/images/Rana's What's app Videos/Vogorously Enjoying his 'walk'.mp4",
    "/images/Rana's What's app Videos/Wee Willie Winkie Talking to dadi.mp4",
    "/images/Rana's What's app Videos/Wee Willie Winkie.mp4",
    "/images/Rana's What's app Videos/What Did Your Papa Tell you.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-09-11 at 00.09.16.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-09-11 at 00.13.56.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-09-11 at 00.15.17.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-09-11 at 00.17.34.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-09-11 at 00.27.32.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-09-11 at 00.29.09.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-09-11 at 00.29.11.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-09-11 at 00.43.53.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-11-14 at 16.21.43.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-11-14 at 16.21.44 (1).mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-11-14 at 16.21.44 (2).mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-11-14 at 16.21.44.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-11-14 at 16.21.45 (1).mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-11-14 at 16.21.45.mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-11-14 at 16.21.46 (1).mp4",
    "/images/Rana's What's app Videos/WhatsApp Video 2023-11-14 at 16.21.46.mp4",
    "/images/Rana's What's app Videos/Where is the Rana.mp4",
    "/images/Rana's What's app Videos/Where's Mama ××.mp4",
    "/images/Rana's What's app Videos/Whistling with Amahle - Got her to smile.mp4",
    "/images/Rana's What's app Videos/Whistling with Amahle.mp4",
    "/images/Rana's What's app Videos/Who made this.mp4",
    "/images/Rana's What's app Videos/With his Bade Dada.mp4",
    "/images/Rana's What's app Videos/With Nana in offc.mp4",
    "/images/Rana's What's app Videos/With the filmy junior brigade.mp4",
    "/images/Rana's What's app Videos/गुड़ गुडी  massage.mp4"
  ],
  "Rana_Pics": [
    "/images/Rana_Pics/1zn2rtMfXW7vh5ID9SNmWRNr6yKe53zvKP-ltpH3SWE=_plaintext_638203426794763696.jpg",
    "/images/Rana_Pics/4 Jain Generations.jpg",
    "/images/Rana_Pics/4WvoGZ-WvUCDkoDPNOoSA1112KhGVeCQw3vjvQMzxQ8=_plaintext_638203427461441609.jpg",
    "/images/Rana_Pics/5hD61k8mMlcs5aCz37jpkl7_DhAbX4XpAHqqTBgzi-Q=_plaintext_638203428746966653.jpg",
    "/images/Rana_Pics/5uEymynf_RAa4gINxbMNRwwWDRUPpiiNjIV_MjN1WNk=_plaintext_638203426853026636.jpg",
    "/images/Rana_Pics/9hkXAgGdhfOr0YpIuS05gk536GgMWa8bk5DjuCL0KYM=_plaintext_638203426528652212.jpg",
    "/images/Rana_Pics/AeQZIJ4sPUchbi6rWtMbfC_6_7h_Ls9G_Flcy7MLfNQ=_plaintext_638203426826978855.jpg",
    "/images/Rana_Pics/BhXCpQas2MXJ4N-zBRzP_0nPTmwcFA7HyUA0UWobCzs=_plaintext_638203426801971210.jpg",
    "/images/Rana_Pics/D0YOjfpW1WBXQBcpn38Lh8VQGT3gjf8Xn6sizuyfvZg=_plaintext_638203426838967629.jpg",
    "/images/Rana_Pics/gDjXSuFN5SnfqDjS-Vxku6lf4Gmvz8DldOr6ocRe2sQ=_plaintext_638203426891521913.jpg",
    "/images/Rana_Pics/gWgDBB0mKF6r65ucMK7sZMDGKURNWCrab_aNJjXlBRY=_plaintext_638203427527487704.jpg",
    "/images/Rana_Pics/h0zF6H_4EosxPiJcjFvXfaEnOK--cuSxX1ZA0fhV1Mc=_plaintext_638203426827511966.jpg",
    "/images/Rana_Pics/hCWn9RiXggm8V6LjQs9EcYSqs1PSqH33CdGiuXVgwuU=_plaintext_638203426848098053.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0013.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0014.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0015.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0016.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0017.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0018.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0019.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0020.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0021.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0022.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0023.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0024.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0025.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0026.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0027.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0028.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0029.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0030.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0031.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0032.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0033.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0034.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0035.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0036.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0037.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0038.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0039.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0040.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0041.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0042.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0043.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0044.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0045.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0046.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0047.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0048.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0049.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0050.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0051.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0052.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0053.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0054.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0055.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0056.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0057.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0058.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0059.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0060.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0061.jpg",
    "/images/Rana_Pics/IMG-20230522-WA0062.jpg",
    "/images/Rana_Pics/kz-Axcf_VHNOp5_km0O6zDxSjihCDRvUmpViKjeA2OQ=_plaintext_638203427515853156.jpg",
    "/images/Rana_Pics/mtgBj11043uua_SzrCnZMciBYJzvg8uR3taf7Vogy9I=_plaintext_638203426813481408.jpg",
    "/images/Rana_Pics/np--ZWNAd2lizdsmF5_rerGJFbHlvHEdMQMt8OQO0dc=_plaintext_638203426815299256.jpg",
    "/images/Rana_Pics/r4iM8caDeeEwsP9_9lvhiUUnmPCu-ILE-3uAME_igrE=_plaintext_638203427530844045.jpg",
    "/images/Rana_Pics/SPekq8ysM7atrEmeUc-8BCW5C-VcmdhWKdI-rBUS6B0=_plaintext_638203426585326690.jpg",
    "/images/Rana_Pics/VID-20230522-WA0008.mp4",
    "/images/Rana_Pics/WduYIrls8yBaVjYF9cveA4vUvviAyEj4_PxqBl30jSs=_plaintext_638203427473031350.jpg",
    "/images/Rana_Pics/x1aMNPBRZmBgsqHiLA0wbfkq-xjShN60BZikbVOBcsU=_plaintext_638203427464070605.jpg",
    "/images/Rana_Pics/xKYgIVIRMSmqC9u2bVMSBgajFuHc0p7poBwBeQPnlYk=_plaintext_638203426863031034.jpg",
    "/images/Rana_Pics/ZO1t5Ew_IPL2hf8R9xRwmkYq0XZWJo8LPaAkFRQgm-o=_plaintext_638203427519096122.jpg"
  ],
  "slider": [
    "/images/slider/IMG-20230522-WA0043.jpg"
  ]
},
  video: {
  "root": [
    "/video/190301_1_25_11.mp4",
    "/video/RANA MOVIE SHORT EDIT.mp4"
  ],
  "Rana Clips": [
    "/video/Rana Clips/Face Therapy For ME.mp4",
    "/video/Rana Clips/First Clsss from Nana - Tongue.mp4",
    "/video/Rana Clips/Morning Class 1.mp4",
    "/video/Rana Clips/Morning Exercise.mp4",
    "/video/Rana Clips/Squareface Rana.mp4",
    "/video/Rana Clips/The Crying sausage.mp4"
  ]
}
};
